### ISSUE TITLE
Missing input 'new-version' breaks call to validate_versions.py

### ISSUE THREAD

**Issue by RobinGranstromKall** [AlirezaTheH/auto-bump-versions#1]
Hi!

I thought your action looked neat and would like to use it.
I was especially interested in the automatic version bumping via keepachangelog.

But the issue i'm facing is that since i'm not supplying the `new-version` input the call to `validate_versions.py@main` breaks due to GITHUB_REPOSITORY is not defined.
See:
> Run python3 /home/runner/work/_actions/alirezatheh/auto-bump-versions/v1/scripts/validate_versions.py  *** my/repository
Usage: validate_versions.py [OPTIONS] NEW_VERSION GITHUB_TOKEN
                            GITHUB_REPOSITORY
Try 'validate_versions.py --help' for help.
Error: Missing argument 'GITHUB_REPOSITORY'.

My proposed solution would be to move the `new-version` argument to be last in the call so it being undefined wouldn't cause the following arguments to end up in the wrong place.

I could make a PR for that, i just wanted to make sure that was ok first 👍

**Comment by alirezatheh** [comment]
Hi @RobinGranstromKall!
Thank you for reporting this issue. Yes I'd appreciate a PR. make sure to add the default `None` for `new_version` parameter. cheers.

**Comment by RobinGranstromKall** [comment]
I will make sure to default the parameter, will upload a PR later in the day 👍

**Comment by RobinGranstromKall** [comment]
I have a PR ready, but sadly i don't have the right permissions to push to this remote. 😢

**Comment by alirezatheh** [comment]
Just:
1 - Fork the repo
2 - Create a new branch
3 - Make your changes and push
4 - Create a new pull request!
Then I'll merge it.

**Comment by RobinGranstromKall** [comment]
I don't know what was going on in my head, but i couldn't find the fork button and thought you had disabled that option..
But now the PR is up and it should be all fine!

**Comment by alirezatheh** [comment]
Thank you Robin 🎉
I can now close this issue.
